<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

// Remove default loop.
remove_action( 'genesis_loop', 'genesis_do_loop' );

add_action( 'genesis_loop', 'genesis_404' );
/**
 * This function outputs a 404 "Not Found" error message.
 *
 * @since 1.6
 */
function genesis_404() {

	?><div class="full-container">
	<div class="custom-container">
		<h2>
			Oops! That page can’t be found.
		</h2>
		 <p class="mt-5" >Sorry, the page you were looking for doesn't exist. Try searching below:</p>
		<div class="filters mt-5">
			<?php echo do_shortcode('[searchandfilter field="Search"]');?>
		</div>
	</div>
</div>
<?php
}

genesis();
